# Traducciones de Mis cuestionarios. Clave = texto en castellano; valores = (en, fr, pt, it, de).
# Tras cambiar algo, ejecuta: python aplicar.py
# clave (castellano) : (en, fr, pt, it, de)
T = {
'Quitar marcas': ('Clear marks','Retirer les marques','Limpar marcas','Togli i segni','Markierungen entfernen'),
'Practicar': ('Practice','S’entraîner','Praticar','Esercitati','Üben'),
'Editar cuestionarios': ('Edit quizzes','Modifier les questionnaires','Editar questionários','Modifica i quiz','Quizze bearbeiten'),
'Pasar entre el PC y el móvil': ('Transfer between PC and phone','Transférer entre le PC et le mobile','Passar entre o PC e o telemóvel','Trasferisci tra PC e telefono','Zwischen PC und Handy übertragen'),
'Al recibir se añade lo nuevo; si un cuestionario ya existe con otro contenido, se pregunta antes de reemplazarlo. Nunca se borra nada.': (
 'When receiving, new items are added; if a quiz already exists with different content, you are asked before replacing it. Nothing is ever deleted.',
 'À la réception, les nouveautés sont ajoutées ; si un questionnaire existe déjà avec un autre contenu, on vous demande avant de le remplacer. Rien n’est jamais supprimé.',
 'Ao receber, o que é novo é adicionado; se um questionário já existir com outro conteúdo, pergunta-se antes de o substituir. Nunca se apaga nada.',
 'Quando ricevi, le novità vengono aggiunte; se un quiz esiste già con un contenuto diverso, ti viene chiesto prima di sostituirlo. Non si cancella mai nulla.',
 'Beim Empfangen wird Neues hinzugefügt; gibt es ein Quiz schon mit anderem Inhalt, wirst du vor dem Ersetzen gefragt. Es wird nie etwas gelöscht.'),
'Por Wi‑Fi': ('Via Wi‑Fi','Par Wi‑Fi','Por Wi‑Fi','Via Wi‑Fi','Per WLAN'),
'(PC y móvil en la misma red)': ('(PC and phone on the same network)','(PC et mobile sur le même réseau)','(PC e telemóvel na mesma rede)','(PC e telefono sulla stessa rete)','(PC und Handy im selben Netz)'),
'En el PC pulsa <b>«Conectar con el móvil por Wi‑Fi»</b>.': ('On the PC, click <b>“Connect to phone via Wi‑Fi”</b>.','Sur le PC, cliquez sur <b>« Connecter le mobile par Wi‑Fi »</b>.','No PC, carrega em <b>«Ligar ao telemóvel por Wi‑Fi»</b>.','Sul PC, premi <b>«Collega al telefono via Wi‑Fi»</b>.','Klicke am PC auf <b>„Mit dem Handy per WLAN verbinden“</b>.'),
'Escribe aquí el PIN que sale en el PC y elige.': ('Type here the PIN shown on the PC and choose.','Saisissez ici le code PIN affiché sur le PC et choisissez.','Escreve aqui o PIN que aparece no PC e escolhe.','Scrivi qui il PIN che compare sul PC e scegli.','Gib hier die PIN vom PC ein und wähle.'),
'¿No encuentra el PC?': ('Can’t find the PC?','Le PC est introuvable ?','Não encontra o PC?','Non trova il PC?','PC wird nicht gefunden?'),
'Escribe la dirección que sale en el PC:': ('Type the address shown on the PC:','Saisissez l’adresse affichée sur le PC :','Escreve o endereço que aparece no PC:','Scrivi l’indirizzo che compare sul PC:','Gib die Adresse ein, die am PC angezeigt wird:'),
'p. ej. 192.168.1.35:8765': ('e.g. 192.168.1.35:8765','ex. 192.168.1.35:8765','ex. 192.168.1.35:8765','es. 192.168.1.35:8765','z. B. 192.168.1.35:8765'),
'Recibir del PC': ('Receive from PC','Recevoir du PC','Receber do PC','Ricevi dal PC','Vom PC empfangen'),
'Enviar al PC': ('Send to PC','Envoyer au PC','Enviar para o PC','Invia al PC','An den PC senden'),
'Por cable USB': ('Via USB cable','Par câble USB','Por cabo USB','Con cavo USB','Per USB-Kabel'),
'<b>Recibir:</b> en el PC pulsa «Pasar todo al móvil por USB», copia la carpeta «Para el móvil» a Descargas del móvil y elígela aquí.': (
 '<b>Receive:</b> on the PC click “Send everything to phone via USB”, copy the “Para el móvil” folder to the phone’s Download folder and choose it here.',
 '<b>Recevoir :</b> sur le PC, cliquez sur « Tout envoyer au mobile par USB », copiez le dossier « Para el móvil » dans Download (Téléchargements) du mobile et choisissez-le ici.',
 '<b>Receber:</b> no PC carrega em «Passar tudo para o telemóvel por USB», copia a pasta «Para el móvil» para Download (Transferências) do telemóvel e escolhe-a aqui.',
 '<b>Ricevi:</b> sul PC premi «Passa tutto al telefono via USB», copia la cartella «Para el móvil» in Download del telefono e sceglila qui.',
 '<b>Empfangen:</b> Klicke am PC auf „Alles per USB aufs Handy“, kopiere den Ordner „Para el móvil“ in den Download-Ordner des Handys und wähle ihn hier aus.'),
'<b>Enviar:</b> se crea «Mis cuestionarios (del móvil)» en la carpeta que elijas (Descargas); cópiala al PC y en el PC pulsa «Recibir del móvil (carpeta)».': (
 '<b>Send:</b> the folder “Mis cuestionarios (del móvil)” is created in the folder you choose (Download); copy it to the PC and on the PC click “Receive from phone (folder)”.',
 '<b>Envoyer :</b> le dossier « Mis cuestionarios (del móvil) » est créé dans le dossier choisi (Download) ; copiez-le sur le PC et, sur le PC, cliquez sur « Recevoir du mobile (dossier) ».',
 '<b>Enviar:</b> é criada a pasta «Mis cuestionarios (del móvil)» na pasta que escolheres (Download); copia-a para o PC e no PC carrega em «Receber do telemóvel (pasta)».',
 '<b>Invia:</b> viene creata la cartella «Mis cuestionarios (del móvil)» nella cartella che scegli (Download); copiala sul PC e sul PC premi «Ricevi dal telefono (cartella)».',
 '<b>Senden:</b> Im gewählten Ordner (Download) wird „Mis cuestionarios (del móvil)“ angelegt; kopiere ihn auf den PC und klicke dort auf „Vom Handy empfangen (Ordner)“.'),
'Recibir: elegir carpeta…': ('Receive: choose folder…','Recevoir : choisir un dossier…','Receber: escolher pasta…','Ricevi: scegli cartella…','Empfangen: Ordner wählen…'),
'Enviar: copiar todo a una carpeta…': ('Send: copy everything to a folder…','Envoyer : tout copier dans un dossier…','Enviar: copiar tudo para uma pasta…','Invia: copia tutto in una cartella…','Senden: alles in einen Ordner kopieren…'),
'Cerrar': ('Close','Fermer','Fechar','Chiudi','Schließen'),
'Creador de cuestionarios': ('Quiz maker','Créateur de questionnaires','Criador de questionários','Crea quiz','Quiz-Ersteller'),
'Organiza materias, temas y cuestionarios en carpetas y exporta un HTML que funciona sin conexión en móvil y ordenador.': (
 'Organise subjects, topics and quizzes in folders and export an HTML file that works offline on phone and computer.',
 'Organisez matières, thèmes et questionnaires en dossiers et exportez un HTML qui fonctionne hors ligne sur mobile et ordinateur.',
 'Organiza disciplinas, temas e questionários em pastas e exporta um HTML que funciona sem ligação no telemóvel e no computador.',
 'Organizza materie, argomenti e quiz in cartelle ed esporta un HTML che funziona offline su telefono e computer.',
 'Ordne Fächer, Themen und Quizze in Ordnern und exportiere eine HTML-Datei, die offline auf Handy und Computer funktioniert.'),
'Mis cuestionarios · asignaturas → temas → cuestionarios': ('My quizzes · subjects → topics → quizzes','Mes questionnaires · matières → thèmes → questionnaires','Os meus questionários · disciplinas → temas → questionários','I miei quiz · materie → argomenti → quiz','Meine Quizze · Fächer → Themen → Quizze'),
'Pasa el ratón por una fila (o tócala) para ver sus botones. Marca la casilla de varios temas o cuestionarios para practicarlos juntos. Solo se pueden importar y exportar temas y cuestionarios. Los nombres no se pueden repetir dentro de la misma carpeta.': (
 'Hover over a row (or tap it) to see its buttons. Tick several topics or quizzes to practise them together. Only topics and quizzes can be imported and exported. Names can’t be repeated within the same folder.',
 'Survolez une ligne (ou touchez-la) pour voir ses boutons. Cochez plusieurs thèmes ou questionnaires pour vous entraîner dessus ensemble. Seuls les thèmes et questionnaires peuvent être importés et exportés. Les noms ne peuvent pas se répéter dans un même dossier.',
 'Passa o rato por uma linha (ou toca nela) para ver os botões. Marca vários temas ou questionários para os praticar juntos. Só se podem importar e exportar temas e questionários. Os nomes não se podem repetir dentro da mesma pasta.',
 'Passa il mouse su una riga (o toccala) per vederne i pulsanti. Spunta più argomenti o quiz per esercitarti insieme. Si possono importare ed esportare solo argomenti e quiz. I nomi non si possono ripetere nella stessa cartella.',
 'Fahre mit der Maus über eine Zeile (oder tippe darauf), um ihre Schaltflächen zu sehen. Hake mehrere Themen oder Quizze an, um sie zusammen zu üben. Nur Themen und Quizze können importiert und exportiert werden. Namen dürfen sich im selben Ordner nicht wiederholen.'),
'Abrir carpeta en el PC': ('Open folder on PC','Ouvrir le dossier sur le PC','Abrir pasta no PC','Apri cartella sul PC','Ordner am PC öffnen'),
'Conectar con el móvil por Wi‑Fi': ('Connect to phone via Wi‑Fi','Connecter le mobile par Wi‑Fi','Ligar ao telemóvel por Wi‑Fi','Collega al telefono via Wi‑Fi','Mit dem Handy per WLAN verbinden'),
'Pasar todo al móvil por USB': ('Send everything to phone via USB','Tout envoyer au mobile par USB','Passar tudo para o telemóvel por USB','Passa tutto al telefono via USB','Alles per USB aufs Handy'),
'Recibir del móvil (carpeta)': ('Receive from phone (folder)','Recevoir du mobile (dossier)','Receber do telemóvel (pasta)','Ricevi dal telefono (cartella)','Vom Handy empfangen (Ordner)'),
'Añadir tarjeta:': ('Add card:','Ajouter une carte :','Adicionar cartão:','Aggiungi scheda:','Karte hinzufügen:'),
'Test A, B, C': ('Multiple choice A, B, C','QCM A, B, C','Escolha múltipla A, B, C','Scelta multipla A, B, C','Multiple Choice A, B, C'),
'Verdadero o falso': ('True or false','Vrai ou faux','Verdadeiro ou falso','Vero o falso','Richtig oder falsch'),
'Pasos': ('Steps','Étapes','Passos','Passaggi','Schritte'),
'Relacionar': ('Match','Associer','Relacionar','Abbina','Zuordnen'),
'Clasificar': ('Sort','Classer','Classificar','Classifica','Einordnen'),
'Foto': ('Photo','Photo','Foto','Foto','Foto'),
'Exportar HTML': ('Export HTML','Exporter en HTML','Exportar HTML','Esporta HTML','HTML exportieren'),
'Test': ('Multiple choice','QCM','Escolha múltipla','Scelta multipla','Multiple Choice'),
'Procedimiento': ('Procedure','Procédure','Procedimento','Procedimento','Vorgehen'),
'varias correctas': ('several correct','plusieurs bonnes réponses','várias corretas','più risposte corrette','mehrere richtig'),
'Correcto': ('Correct','Correct','Correto','Corretto','Richtig'),
'Incorrecto': ('Incorrect','Incorrect','Incorreto','Sbagliato','Falsch'),
'Ver nota': ('See score','Voir la note','Ver nota','Vedi il voto','Note ansehen'),
'Siguiente': ('Next','Suivant','Seguinte','Avanti','Weiter'),
'V': ('T','V','V','V','R'),
'Verdadero': ('True','Vrai','Verdadeiro','Vero','Richtig'),
'F': ('F','F','F','F','F'),
'Falso': ('False','Faux','Falso','Falso','Falsch'),
'Era verdadero': ('It was true','C’était vrai','Era verdadeiro','Era vero','Es war richtig'),
'Era falso': ('It was false','C’était faux','Era falso','Era falso','Es war falsch'),
'Comprobar': ('Check','Vérifier','Verificar','Verifica','Prüfen'),
'Las correctas están en verde': ('The correct ones are in green','Les bonnes réponses sont en vert','As corretas estão a verde','Quelle corrette sono in verde','Die richtigen sind grün'),
'Toca los pasos en el orden correcto.': ('Tap the steps in the right order.','Touchez les étapes dans le bon ordre.','Toca nos passos pela ordem correta.','Tocca i passaggi nell’ordine giusto.','Tippe die Schritte in der richtigen Reihenfolge an.'),
'Hubo errores al ordenar': ('There were mistakes in the order','Il y a eu des erreurs dans l’ordre','Houve erros ao ordenar','Ci sono stati errori nell’ordine','Beim Ordnen gab es Fehler'),
'Toca un elemento de la izquierda y luego su pareja de la derecha.': ('Tap an item on the left and then its match on the right.','Touchez un élément à gauche puis son correspondant à droite.','Toca num elemento da esquerda e depois no seu par da direita.','Tocca un elemento a sinistra e poi la sua coppia a destra.','Tippe links ein Element an und dann sein Gegenstück rechts.'),
'Hubo errores al emparejar': ('There were mistakes when matching','Il y a eu des erreurs d’association','Houve erros ao emparelhar','Ci sono stati errori negli abbinamenti','Beim Zuordnen gab es Fehler'),
'Toca un elemento y luego el grupo al que pertenece. Puedes moverlos antes de comprobar.': ('Tap an item and then the group it belongs to. You can move them before checking.','Touchez un élément puis le groupe auquel il appartient. Vous pouvez les déplacer avant de vérifier.','Toca num elemento e depois no grupo a que pertence. Podes movê-los antes de verificar.','Tocca un elemento e poi il gruppo a cui appartiene. Puoi spostarli prima di verificare.','Tippe ein Element an und dann die Gruppe, zu der es gehört. Vor dem Prüfen kannst du sie verschieben.'),
'Todos colocados': ('All placed','Tous placés','Todos colocados','Tutti collocati','Alle eingeordnet'),
'{0} de {1} bien colocados': ('{0} of {1} placed correctly','{0} sur {1} bien placés','{0} de {1} bem colocados','{0} su {1} collocati bene','{0} von {1} richtig eingeordnet'),
'Tarjeta {0} de {1}': ('Card {0} of {1}','Carte {0} sur {1}','Cartão {0} de {1}','Scheda {0} di {1}','Karte {0} von {1}'),
'Nueva mejor nota (antes {0})': ('New best score (was {0})','Nouvelle meilleure note (avant {0})','Nova melhor nota (antes {0})','Nuovo miglior voto (prima {0})','Neue Bestnote (vorher {0})'),
'Tu mejor nota: {0}': ('Your best score: {0}','Votre meilleure note : {0}','A tua melhor nota: {0}','Il tuo miglior voto: {0}','Deine Bestnote: {0}'),
'Completado': ('Completed','Terminé','Concluído','Completato','Fertig'),
'Resultado final': ('Final result','Résultat final','Resultado final','Risultato finale','Endergebnis'),
'{0} de {1} tarjetas totalmente correctas': ('{0} of {1} cards fully correct','{0} cartes sur {1} entièrement correctes','{0} de {1} cartões totalmente corretos','{0} schede su {1} completamente corrette','{0} von {1} Karten ganz richtig'),
'Solo había fotos: no hay nota.': ('There were only photos: no score.','Il n’y avait que des photos : pas de note.','Só havia fotos: não há nota.','C’erano solo foto: nessun voto.','Es gab nur Fotos: keine Note.'),
'Para repasar': ('To review','À revoir','Para rever','Da ripassare','Zum Wiederholen'),
'Sin ningún fallo.': ('No mistakes at all.','Aucune erreur.','Sem nenhum erro.','Nessun errore.','Kein einziger Fehler.'),
'Siguiente cuestionario: {0}': ('Next quiz: {0}','Questionnaire suivant : {0}','Questionário seguinte: {0}','Quiz successivo: {0}','Nächstes Quiz: {0}'),
'Ver resumen': ('See summary','Voir le résumé','Ver resumo','Vedi riepilogo','Zusammenfassung ansehen'),
'Repetir todo': ('Repeat all','Tout recommencer','Repetir tudo','Ripeti tutto','Alles wiederholen'),
'Repetir solo falladas': ('Repeat only the wrong ones','Refaire seulement les erreurs','Repetir só as erradas','Ripeti solo quelle sbagliate','Nur falsche wiederholen'),
'Resumen': ('Summary','Résumé','Resumo','Riepilogo','Zusammenfassung'),
'Nota media, ponderada por número de tarjetas': ('Average score, weighted by number of cards','Note moyenne, pondérée par le nombre de cartes','Nota média, ponderada pelo número de cartões','Voto medio, ponderato per numero di schede','Durchschnittsnote, gewichtet nach Anzahl der Karten'),
'{0} cuestionarios en total': ('{0} quizzes in total','{0} questionnaires au total','{0} questionários no total','{0} quiz in totale','{0} Quizze insgesamt'),
'Marcar para practicar': ('Tick to practise','Cocher pour s’entraîner','Marcar para praticar','Spunta per esercitarti','Zum Üben markieren'),
'Inicio': ('Home','Accueil','Início','Inizio','Start'),
'Marca varios temas o cuestionarios y practícalos seguidos.': ('Tick several topics or quizzes and practise them in a row.','Cochez plusieurs thèmes ou questionnaires et entraînez-vous à la suite.','Marca vários temas ou questionários e pratica-os seguidos.','Spunta più argomenti o quiz ed esercitati di fila.','Markiere mehrere Themen oder Quizze und übe sie nacheinander.'),
'{0} cuestionarios': ('{0} quizzes','{0} questionnaires','{0} questionários','{0} quiz','{0} Quizze'),
'{0} tarjetas': ('{0} cards','{0} cartes','{0} cartões','{0} schede','{0} Karten'),
'mejor {0}': ('best {0}','meilleure {0}','melhor {0}','migliore {0}','beste {0}'),
'Practicar seleccionados ({0})': ('Practise selected ({0})','S’entraîner sur la sélection ({0})','Praticar selecionados ({0})','Esercitati sui selezionati ({0})','Ausgewählte üben ({0})'),
'Hacer esta carpeta ({0} cuestionarios seguidos)': ('Do this folder ({0} quizzes in a row)','Faire ce dossier ({0} questionnaires à la suite)','Fazer esta pasta ({0} questionários seguidos)','Fai questa cartella ({0} quiz di fila)','Diesen Ordner machen ({0} Quizze nacheinander)'),
'Hacer todo ({0} cuestionarios seguidos)': ('Do everything ({0} quizzes in a row)','Tout faire ({0} questionnaires à la suite)','Fazer tudo ({0} questionários seguidos)','Fai tutto ({0} quiz di fila)','Alles machen ({0} Quizze nacheinander)'),
'Empezar de nuevo': ('Start again','Recommencer','Começar de novo','Ricomincia','Neu beginnen'),
'Volver al menú': ('Back to menu','Retour au menu','Voltar ao menu','Torna al menu','Zurück zum Menü'),
'Esta biblioteca no tiene tarjetas.': ('This library has no cards.','Cette bibliothèque n’a pas de cartes.','Esta biblioteca não tem cartões.','Questa raccolta non ha schede.','Diese Sammlung hat keine Karten.'),
'¿Empezar de nuevo este cuestionario? Se pierde el intento actual.': ('Start this quiz again? The current attempt will be lost.','Recommencer ce questionnaire ? La tentative en cours sera perdue.','Começar este questionário de novo? A tentativa atual perde-se.','Ricominciare questo quiz? Il tentativo attuale andrà perso.','Dieses Quiz neu beginnen? Der aktuelle Versuch geht verloren.'),
'¿Salir al menú? Se pierde el intento actual.': ('Go back to the menu? The current attempt will be lost.','Revenir au menu ? La tentative en cours sera perdue.','Sair para o menu? A tentativa atual perde-se.','Tornare al menu? Il tentativo attuale andrà perso.','Zum Menü zurück? Der aktuelle Versuch geht verloren.'),
'Idioma': ('Language','Langue','Idioma','Lingua','Sprache'),
'Selección: {0}': ('Selected: {0}','Sélection : {0}','Seleção: {0}','Selezione: {0}','Auswahl: {0}'),
'Mis cuestionarios': ('My quizzes','Mes questionnaires','Os meus questionários','I miei quiz','Meine Quizze'),
'Sin título': ('Untitled','Sans titre','Sem título','Senza titolo','Ohne Titel'),
'{0} cuestionarios, {1} tarjetas completas': ('{0} quizzes, {1} complete cards','{0} questionnaires, {1} cartes complètes','{0} questionários, {1} cartões completos','{0} quiz, {1} schede complete','{0} Quizze, {1} vollständige Karten'),
'Correcta': ('Correct','Correcte','Correta','Corretta','Richtig'),
'Texto de la opción': ('Option text','Texte de l’option','Texto da opção','Testo dell’opzione','Text der Option'),
'Añadir opción': ('Add option','Ajouter une option','Adicionar opção','Aggiungi opzione','Option hinzufügen'),
'Título del paso': ('Step title','Titre de l’étape','Título do passo','Titolo del passaggio','Titel des Schritts'),
'Detalle del paso': ('Step detail','Détail de l’étape','Detalhe do passo','Dettaglio del passaggio','Details zum Schritt'),
'Teclado matemático': ('Math keyboard','Clavier mathématique','Teclado matemático','Tastiera matematica','Mathe-Tastatur'),
'Añadir paso': ('Add step','Ajouter une étape','Adicionar passo','Aggiungi passaggio','Schritt hinzufügen'),
'Elemento': ('Item','Élément','Elemento','Elemento','Element'),
'Su pareja': ('Its match','Son correspondant','O seu par','La sua coppia','Sein Gegenstück'),
'Añadir pareja': ('Add pair','Ajouter une paire','Adicionar par','Aggiungi coppia','Paar hinzufügen'),
'Nombre del grupo': ('Group name','Nom du groupe','Nome do grupo','Nome del gruppo','Name der Gruppe'),
'Elemento de este grupo': ('Item in this group','Élément de ce groupe','Elemento deste grupo','Elemento di questo gruppo','Element dieser Gruppe'),
'Añadir elemento': ('Add item','Ajouter un élément','Adicionar elemento','Aggiungi elemento','Element hinzufügen'),
'Añadir grupo': ('Add group','Ajouter un groupe','Adicionar grupo','Aggiungi gruppo','Gruppe hinzufügen'),
'Todavía no hay foto.': ('No photo yet.','Pas encore de photo.','Ainda não há foto.','Ancora nessuna foto.','Noch kein Foto.'),
'Cambiar foto': ('Change photo','Changer la photo','Mudar foto','Cambia foto','Foto ändern'),
'Elegir foto…': ('Choose photo…','Choisir une photo…','Escolher foto…','Scegli foto…','Foto wählen…'),
'Quitar foto': ('Remove photo','Retirer la photo','Remover foto','Togli foto','Foto entfernen'),
'Explicación (opcional)': ('Explanation (optional)','Explication (facultatif)','Explicação (opcional)','Spiegazione (facoltativa)','Erklärung (optional)'),
'Eliminar': ('Delete','Supprimer','Eliminar','Elimina','Löschen'),
'Todavía no hay tarjetas. Elige un tipo arriba para empezar.': ('No cards yet. Choose a type above to start.','Pas encore de cartes. Choisissez un type ci-dessus pour commencer.','Ainda não há cartões. Escolhe um tipo acima para começar.','Ancora nessuna scheda. Scegli un tipo qui sopra per iniziare.','Noch keine Karten. Wähle oben einen Typ, um zu beginnen.'),
'sen': ('sin','sin','sen','sin','sin'),
'Detalle o cálculo (opcional)': ('Detail or calculation (optional)','Détail ou calcul (facultatif)','Detalhe ou cálculo (opcional)','Dettaglio o calcolo (facoltativo)','Detail oder Rechnung (optional)'),
'No he podido abrir esa imagen.': ('I couldn’t open that image.','Impossible d’ouvrir cette image.','Não consegui abrir essa imagem.','Non sono riuscito ad aprire quell’immagine.','Das Bild konnte nicht geöffnet werden.'),
'¿Eliminar esta tarjeta?': ('Delete this card?','Supprimer cette carte ?','Eliminar este cartão?','Eliminare questa scheda?','Diese Karte löschen?'),
'Renombrar': ('Rename','Renommer','Mudar o nome','Rinomina','Umbenennen'),
'Exportar (elige tema o cuestionario)': ('Export (choose topic or quiz)','Exporter (choisissez thème ou questionnaire)','Exportar (escolhe tema ou questionário)','Esporta (scegli argomento o quiz)','Exportieren (Thema oder Quiz wählen)'),
'Practicar selección ({0})': ('Practise selection ({0})','S’entraîner sur la sélection ({0})','Praticar seleção ({0})','Esercitati sulla selezione ({0})','Auswahl üben ({0})'),
'Nuevo nombre': ('New name','Nouveau nom','Novo nome','Nuovo nome','Neuer Name'),
'¿Eliminar «{0}»?': ('Delete “{0}”?','Supprimer « {0} » ?','Eliminar «{0}»?','Eliminare «{0}»?','„{0}“ löschen?'),
'¿Eliminar «{0}» con todo lo que contiene?': ('Delete “{0}” and everything in it?','Supprimer « {0} » avec tout son contenu ?','Eliminar «{0}» com tudo o que contém?','Eliminare «{0}» con tutto il contenuto?','„{0}“ mit allem Inhalt löschen?'),
'«{0}» ya existe en el destino.': ('“{0}” already exists in the destination.','« {0} » existe déjà dans la destination.','«{0}» já existe no destino.','«{0}» esiste già nella destinazione.','„{0}“ gibt es am Ziel schon.'),
'Práctica': ('Practice','Entraînement','Prática','Esercitazione','Übung'),
'No he podido guardar el archivo:': ('I couldn’t save the file:','Impossible d’enregistrer le fichier :','Não consegui guardar o ficheiro:','Non sono riuscito a salvare il file:','Die Datei konnte nicht gespeichert werden:'),
'Guardado en Descargas: {0}': ('Saved to Downloads: {0}','Enregistré dans Téléchargements : {0}','Guardado em Transferências: {0}','Salvato in Download: {0}','In Downloads gespeichert: {0}'),
'No hay ninguna tarjeta completa en lo seleccionado. Test: 2 opciones y una correcta. Pasos y relacionar: al menos 2. Clasificar: 2 grupos con elementos.': (
 'There are no complete cards in the selection. Multiple choice: 2 options and one correct. Steps and match: at least 2. Sort: 2 groups with items.',
 'Aucune carte complète dans la sélection. QCM : 2 options dont une correcte. Étapes et associer : au moins 2. Classer : 2 groupes avec des éléments.',
 'Não há nenhum cartão completo na seleção. Escolha múltipla: 2 opções e uma correta. Passos e relacionar: pelo menos 2. Classificar: 2 grupos com elementos.',
 'Nessuna scheda completa nella selezione. Scelta multipla: 2 opzioni e una corretta. Passaggi e abbina: almeno 2. Classifica: 2 gruppi con elementi.',
 'In der Auswahl gibt es keine vollständige Karte. Multiple Choice: 2 Optionen und eine richtige. Schritte und Zuordnen: mindestens 2. Einordnen: 2 Gruppen mit Elementen.'),
'«{0}» ya existe. ¿Seguro que quieres reemplazarlo?': ('“{0}” already exists. Are you sure you want to replace it?','« {0} » existe déjà. Voulez-vous vraiment le remplacer ?','«{0}» já existe. Tens a certeza de que o queres substituir?','«{0}» esiste già. Vuoi davvero sostituirlo?','„{0}“ gibt es schon. Wirklich ersetzen?'),
'Solo se pueden importar temas y cuestionarios.': ('Only topics and quizzes can be imported.','Seuls les thèmes et questionnaires peuvent être importés.','Só se podem importar temas e questionários.','Si possono importare solo argomenti e quiz.','Nur Themen und Quizze können importiert werden.'),
'Aquí solo se puede importar un tema.': ('Only a topic can be imported here.','Ici, on ne peut importer qu’un thème.','Aqui só se pode importar um tema.','Qui si può importare solo un argomento.','Hier kann nur ein Thema importiert werden.'),
'Aquí solo se puede importar un cuestionario.': ('Only a quiz can be imported here.','Ici, on ne peut importer qu’un questionnaire.','Aqui só se pode importar um questionário.','Qui si può importare solo un quiz.','Hier kann nur ein Quiz importiert werden.'),
'No he podido leer «{0}».': ('I couldn’t read “{0}”.','Impossible de lire « {0} ».','Não consegui ler «{0}».','Non sono riuscito a leggere «{0}».','„{0}“ konnte nicht gelesen werden.'),
'guardando…': ('saving…','enregistrement…','a guardar…','salvataggio…','speichert…'),
'No se pudo guardar.': ('Could not save.','Impossible d’enregistrer.','Não foi possível guardar.','Impossibile salvare.','Speichern nicht möglich.'),
'No he podido guardar en la app.': ('I couldn’t save in the app.','Impossible d’enregistrer dans l’app.','Não consegui guardar na app.','Non sono riuscito a salvare nell’app.','In der App konnte nicht gespeichert werden.'),
'No he podido guardar. Si usas el PC, ¿sigue abierta la ventana del servidor?': ('I couldn’t save. If you are on the PC, is the server window still open?','Impossible d’enregistrer. Sur le PC, la fenêtre du serveur est-elle toujours ouverte ?','Não consegui guardar. Se usas o PC, a janela do servidor continua aberta?','Non sono riuscito a salvare. Se usi il PC, la finestra del server è ancora aperta?','Speichern fehlgeschlagen. Ist am PC das Serverfenster noch offen?'),
'No he podido guardar en este navegador (almacenamiento lleno o desactivado; las fotos ocupan mucho). La versión PC y la app guardan en archivos y no tienen ese límite.': (
 'I couldn’t save in this browser (storage full or disabled; photos take a lot of space). The PC version and the app save to files and don’t have that limit.',
 'Impossible d’enregistrer dans ce navigateur (stockage plein ou désactivé ; les photos prennent beaucoup de place). La version PC et l’app enregistrent dans des fichiers, sans cette limite.',
 'Não consegui guardar neste navegador (armazenamento cheio ou desativado; as fotos ocupam muito). A versão PC e a app guardam em ficheiros e não têm esse limite.',
 'Non sono riuscito a salvare in questo browser (memoria piena o disattivata; le foto occupano molto). La versione PC e l’app salvano su file e non hanno questo limite.',
 'In diesem Browser konnte nicht gespeichert werden (Speicher voll oder deaktiviert; Fotos brauchen viel Platz). Die PC-Version und die App speichern in Dateien und haben diese Grenze nicht.'),
'He ajustado la carpeta para cumplir las reglas (asignatura › tema › cuestionario, sin nombres repetidos). Lo que estaba fuera de sitio está en «General».': (
 'I adjusted the folder to follow the rules (subject › topic › quiz, no repeated names). Anything out of place is now in “General”.',
 'J’ai ajusté le dossier pour respecter les règles (matière › thème › questionnaire, sans noms répétés). Ce qui n’était pas à sa place est dans « General ».',
 'Ajustei a pasta para cumprir as regras (disciplina › tema › questionário, sem nomes repetidos). O que estava fora do sítio está em «General».',
 'Ho sistemato la cartella per rispettare le regole (materia › argomento › quiz, senza nomi ripetuti). Ciò che era fuori posto ora è in «General».',
 'Ich habe den Ordner an die Regeln angepasst (Fach › Thema › Quiz, keine doppelten Namen). Was nicht am richtigen Platz war, liegt jetzt in „General“.'),
'Carpeta en el PC: {0}': ('Folder on PC: {0}','Dossier sur le PC : {0}','Pasta no PC: {0}','Cartella sul PC: {0}','Ordner am PC: {0}'),
'No he podido abrir la carpeta.': ('I couldn’t open the folder.','Impossible d’ouvrir le dossier.','Não consegui abrir a pasta.','Non sono riuscito ad aprire la cartella.','Der Ordner konnte nicht geöffnet werden.'),
'No he podido leer lo que ha enviado el móvil.': ('I couldn’t read what the phone sent.','Impossible de lire ce que le mobile a envoyé.','Não consegui ler o que o telemóvel enviou.','Non sono riuscito a leggere ciò che ha inviato il telefono.','Was das Handy gesendet hat, konnte nicht gelesen werden.'),
'Conexión Wi‑Fi cerrada.': ('Wi‑Fi connection closed.','Connexion Wi‑Fi fermée.','Ligação Wi‑Fi fechada.','Connessione Wi‑Fi chiusa.','WLAN-Verbindung geschlossen.'),
'Enviado al móvil: {0}.': ('Sent to phone: {0}.','Envoyé au mobile : {0}.','Enviado para o telemóvel: {0}.','Inviato al telefono: {0}.','Ans Handy gesendet: {0}.'),
'Recibido del móvil: {0}.': ('Received from phone: {0}.','Reçu du mobile : {0}.','Recebido do telemóvel: {0}.','Ricevuto dal telefono: {0}.','Vom Handy empfangen: {0}.'),
'Cerrar conexión Wi‑Fi': ('Close Wi‑Fi connection','Fermer la connexion Wi‑Fi','Fechar ligação Wi‑Fi','Chiudi connessione Wi‑Fi','WLAN-Verbindung schließen'),
'<b>Conectado por Wi‑Fi.</b> En la app del móvil toca <b>⇅ PC</b>, escribe este PIN y elige <b>Recibir del PC</b> o <b>Enviar al PC</b>:': (
 '<b>Connected via Wi‑Fi.</b> In the phone app tap <b>⇅ PC</b>, type this PIN and choose <b>Receive from PC</b> or <b>Send to PC</b>:',
 '<b>Connecté par Wi‑Fi.</b> Dans l’app du mobile, touchez <b>⇅ PC</b>, saisissez ce code PIN et choisissez <b>Recevoir du PC</b> ou <b>Envoyer au PC</b> :',
 '<b>Ligado por Wi‑Fi.</b> Na app do telemóvel toca em <b>⇅ PC</b>, escreve este PIN e escolhe <b>Receber do PC</b> ou <b>Enviar para o PC</b>:',
 '<b>Connesso via Wi‑Fi.</b> Nell’app del telefono tocca <b>⇅ PC</b>, scrivi questo PIN e scegli <b>Ricevi dal PC</b> o <b>Invia al PC</b>:',
 '<b>Per WLAN verbunden.</b> Tippe in der Handy-App auf <b>⇅ PC</b>, gib diese PIN ein und wähle <b>Vom PC empfangen</b> oder <b>An den PC senden</b>:'),
'Enviado al móvil': ('Sent to phone','Envoyé au mobile','Enviado para o telemóvel','Inviato al telefono','Ans Handy gesendet'),
'Recibido del móvil': ('Received from phone','Reçu du mobile','Recebido do telemóvel','Ricevuto dal telefono','Vom Handy empfangen'),
'Esperando al móvil…': ('Waiting for the phone…','En attente du mobile…','À espera do telemóvel…','In attesa del telefono…','Warte auf das Handy…'),
'Se cierra sola en {0} min.': ('Closes by itself in {0} min.','Se ferme toute seule dans {0} min.','Fecha sozinha dentro de {0} min.','Si chiude da sola tra {0} min.','Schließt sich in {0} Min. von selbst.'),
'El móvil y el PC tienen que estar en la misma Wi‑Fi. Si la app no encuentra el PC, escribe en ella:': ('The phone and the PC must be on the same Wi‑Fi. If the app can’t find the PC, type this in it:','Le mobile et le PC doivent être sur le même Wi‑Fi. Si l’app ne trouve pas le PC, saisissez-y :','O telemóvel e o PC têm de estar na mesma Wi‑Fi. Se a app não encontrar o PC, escreve nela:','Telefono e PC devono essere sulla stessa Wi‑Fi. Se l’app non trova il PC, scrivi nell’app:','Handy und PC müssen im selben WLAN sein. Findet die App den PC nicht, gib dort ein:'),
'Si Windows pregunta por el firewall de MyQuizzes, pulsa «Permitir» (redes privadas). Si aun así no conecta, pon tu Wi‑Fi como red privada en Windows.': (
 'If Windows asks about the MyQuizzes firewall, click “Allow” (private networks). If it still doesn’t connect, set your Wi‑Fi as a private network in Windows.',
 'Si Windows pose une question sur le pare-feu pour MyQuizzes, cliquez sur « Autoriser » (réseaux privés). Si ça ne se connecte toujours pas, définissez votre Wi‑Fi comme réseau privé dans Windows.',
 'Se o Windows perguntar pela firewall do MyQuizzes, carrega em «Permitir» (redes privadas). Se mesmo assim não ligar, define a tua Wi‑Fi como rede privada no Windows.',
 'Se Windows chiede del firewall per MyQuizzes, premi «Consenti» (reti private). Se ancora non si collega, imposta la tua Wi‑Fi come rete privata in Windows.',
 'Fragt Windows wegen der Firewall für MyQuizzes, klicke auf „Zulassen“ (private Netzwerke). Klappt es trotzdem nicht, stelle dein WLAN in Windows als privates Netzwerk ein.'),
'No he podido cerrar la conexión Wi‑Fi.': ('I couldn’t close the Wi‑Fi connection.','Impossible de fermer la connexion Wi‑Fi.','Não consegui fechar a ligação Wi‑Fi.','Non sono riuscito a chiudere la connessione Wi‑Fi.','Die WLAN-Verbindung konnte nicht geschlossen werden.'),
'No he podido abrir la conexión Wi‑Fi.': ('I couldn’t open the Wi‑Fi connection.','Impossible d’ouvrir la connexion Wi‑Fi.','Não consegui abrir a ligação Wi‑Fi.','Non sono riuscito ad aprire la connessione Wi‑Fi.','Die WLAN-Verbindung konnte nicht geöffnet werden.'),
'En esa carpeta no hay archivos de cuestionarios (.json o .html). Elige la carpeta «Mis cuestionarios (del móvil)».': ('That folder has no quiz files (.json or .html). Choose the “Mis cuestionarios (del móvil)” folder.','Ce dossier ne contient aucun fichier de questionnaire (.json ou .html). Choisissez le dossier « Mis cuestionarios (del móvil) ».','Essa pasta não tem ficheiros de questionários (.json ou .html). Escolhe a pasta «Mis cuestionarios (del móvil)».','In quella cartella non ci sono file di quiz (.json o .html). Scegli la cartella «Mis cuestionarios (del móvil)».','In diesem Ordner gibt es keine Quiz-Dateien (.json oder .html). Wähle den Ordner „Mis cuestionarios (del móvil)“.'),
'No hay ningún tema con tarjetas completas.': ('There is no topic with complete cards.','Aucun thème n’a de cartes complètes.','Não há nenhum tema com cartões completos.','Nessun argomento ha schede complete.','Kein Thema hat vollständige Karten.'),
'<b>Enviado al móvil por USB.</b> Está en la carpeta «Para el móvil», dentro de Descargas.': ('<b>Sent to the phone via USB.</b> It’s in the “Para el móvil” folder inside Download.','<b>Envoyé au mobile par USB.</b> C’est dans le dossier « Para el móvil », dans Download.','<b>Enviado para o telemóvel por USB.</b> Está na pasta «Para el móvil», dentro de Download.','<b>Inviato al telefono via USB.</b> È nella cartella «Para el móvil», dentro Download.','<b>Per USB ans Handy gesendet.</b> Es liegt im Ordner „Para el móvil“ in Download.'),
'<b>Preparado ({0} temas).</b> Se ha abierto la carpeta «Para el móvil» de tu PC: una subcarpeta por asignatura y un archivo por tema.': (
 '<b>Ready ({0} topics).</b> The “Para el móvil” folder has been opened on your PC: one subfolder per subject and one file per topic.',
 '<b>Prêt ({0} thèmes).</b> Le dossier « Para el móvil » s’est ouvert sur votre PC : un sous-dossier par matière et un fichier par thème.',
 '<b>Preparado ({0} temas).</b> Abriu-se a pasta «Para el móvil» do teu PC: uma subpasta por disciplina e um ficheiro por tema.',
 '<b>Pronto ({0} argomenti).</b> Si è aperta la cartella «Para el móvil» del tuo PC: una sottocartella per materia e un file per argomento.',
 '<b>Fertig ({0} Themen).</b> Der Ordner „Para el móvil“ wurde auf deinem PC geöffnet: ein Unterordner pro Fach und eine Datei pro Thema.'),
'Conecta el móvil con el cable USB.': ('Connect the phone with the USB cable.','Branchez le mobile avec le câble USB.','Liga o telemóvel com o cabo USB.','Collega il telefono con il cavo USB.','Verbinde das Handy mit dem USB-Kabel.'),
'En el móvil, toca la notificación de USB y elige «Transferir archivos».': ('On the phone, tap the USB notification and choose “File transfer”.','Sur le mobile, touchez la notification USB et choisissez « Transfert de fichiers ».','No telemóvel, toca na notificação de USB e escolhe «Transferência de ficheiros».','Sul telefono, tocca la notifica USB e scegli «Trasferimento file».','Tippe am Handy auf die USB-Benachrichtigung und wähle „Dateiübertragung“.'),
'Copia la carpeta <b>Para el móvil</b> entera a <b>Download</b> (Descargas) del móvil.': ('Copy the whole <b>Para el móvil</b> folder to the phone’s <b>Download</b> folder.','Copiez tout le dossier <b>Para el móvil</b> dans <b>Download</b> (Téléchargements) du mobile.','Copia a pasta <b>Para el móvil</b> inteira para <b>Download</b> (Transferências) do telemóvel.','Copia l’intera cartella <b>Para el móvil</b> in <b>Download</b> del telefono.','Kopiere den ganzen Ordner <b>Para el móvil</b> in den Ordner <b>Download</b> des Handys.'),
'En la app del móvil toca <b>⇅ PC › ⇩ Recibir: elegir carpeta…</b> y elige la carpeta <b>Para el móvil</b>: se copian todas las asignaturas, temas y cuestionarios de una vez (también las fotos y lo que esté a medias).': (
 'In the phone app tap <b>⇅ PC › ⇩ Receive: choose folder…</b> and choose the <b>Para el móvil</b> folder: all subjects, topics and quizzes are copied at once (including photos and unfinished work).',
 'Dans l’app du mobile, touchez <b>⇅ PC › ⇩ Recevoir : choisir un dossier…</b> et choisissez le dossier <b>Para el móvil</b> : toutes les matières, thèmes et questionnaires sont copiés d’un coup (photos et travail inachevé compris).',
 'Na app do telemóvel toca em <b>⇅ PC › ⇩ Receber: escolher pasta…</b> e escolhe a pasta <b>Para el móvil</b>: copiam-se todas as disciplinas, temas e questionários de uma vez (também as fotos e o que estiver a meio).',
 'Nell’app del telefono tocca <b>⇅ PC › ⇩ Ricevi: scegli cartella…</b> e scegli la cartella <b>Para el móvil</b>: vengono copiati tutti insieme materie, argomenti e quiz (anche le foto e ciò che è a metà).',
 'Tippe in der Handy-App auf <b>⇅ PC › ⇩ Empfangen: Ordner wählen…</b> und wähle den Ordner <b>Para el móvil</b>: Alle Fächer, Themen und Quizze werden auf einmal kopiert (auch Fotos und Unfertiges).'),
'No he podido preparar los archivos para el móvil.': ('I couldn’t prepare the files for the phone.','Impossible de préparer les fichiers pour le mobile.','Não consegui preparar os ficheiros para o telemóvel.','Non sono riuscito a preparare i file per il telefono.','Die Dateien für das Handy konnten nicht vorbereitet werden.'),
'{0} cuestionario(s) ya existen en el móvil con otro contenido:': ('{0} quiz(zes) already exist on the phone with different content:','{0} questionnaire(s) existe(nt) déjà sur le mobile avec un autre contenu :','{0} questionário(s) já existe(m) no telemóvel com outro conteúdo:','{0} quiz esistono già sul telefono con un contenuto diverso:','{0} Quiz gibt es auf dem Handy schon mit anderem Inhalt:'),
'{0} cuestionario(s) ya existen en el PC con otro contenido:': ('{0} quiz(zes) already exist on the PC with different content:','{0} questionnaire(s) existe(nt) déjà sur le PC avec un autre contenu :','{0} questionário(s) já existe(m) no PC com outro conteúdo:','{0} quiz esistono già sul PC con un contenuto diverso:','{0} Quiz gibt es auf dem PC schon mit anderem Inhalt:'),
'¿Reemplazarlos por los del PC?\n(Aceptar = reemplazar · Cancelar = dejar los del móvil)': ('Replace them with the PC’s?\n(OK = replace · Cancel = keep the phone’s)','Les remplacer par ceux du PC ?\n(OK = remplacer · Annuler = garder ceux du mobile)','Substituí-los pelos do PC?\n(OK = substituir · Cancelar = manter os do telemóvel)','Sostituirli con quelli del PC?\n(OK = sostituisci · Annulla = tieni quelli del telefono)','Durch die vom PC ersetzen?\n(OK = ersetzen · Abbrechen = die vom Handy behalten)'),
'¿Reemplazarlos por los del móvil?\n(Aceptar = reemplazar · Cancelar = dejar los del PC)': ('Replace them with the phone’s?\n(OK = replace · Cancel = keep the PC’s)','Les remplacer par ceux du mobile ?\n(OK = remplacer · Annuler = garder ceux du PC)','Substituí-los pelos do telemóvel?\n(OK = substituir · Cancelar = manter os do PC)','Sostituirli con quelli del telefono?\n(OK = sostituisci · Annulla = tieni quelli del PC)','Durch die vom Handy ersetzen?\n(OK = ersetzen · Abbrechen = die vom PC behalten)'),
'No he encontrado asignaturas ni cuestionarios en «{0}» (he visto {1} carpetas y {2} archivos .json/.html).': ('I found no subjects or quizzes in “{0}” (I saw {1} folders and {2} .json/.html files).','Aucune matière ni aucun questionnaire trouvé dans « {0} » ({1} dossiers et {2} fichiers .json/.html vus).','Não encontrei disciplinas nem questionários em «{0}» (vi {1} pastas e {2} ficheiros .json/.html).','Non ho trovato materie né quiz in «{0}» (ho visto {1} cartelle e {2} file .json/.html).','In „{0}“ wurden keine Fächer oder Quizze gefunden (gesehen: {1} Ordner und {2} .json/.html-Dateien).'),
'Elige la carpeta «Mis cuestionarios» (o «Para el móvil») que copiaste.': ('Choose the “Mis cuestionarios” (or “Para el móvil”) folder you copied.','Choisissez le dossier « Mis cuestionarios » (ou « Para el móvil ») que vous avez copié.','Escolhe a pasta «Mis cuestionarios» (ou «Para el móvil») que copiaste.','Scegli la cartella «Mis cuestionarios» (o «Para el móvil») che hai copiato.','Wähle den kopierten Ordner „Mis cuestionarios“ (oder „Para el móvil“).'),
'No he encontrado asignaturas ni cuestionarios.': ('I found no subjects or quizzes.','Aucune matière ni aucun questionnaire trouvé.','Não encontrei disciplinas nem questionários.','Non ho trovato materie né quiz.','Keine Fächer oder Quizze gefunden.'),
'{0} asignatura(s) nueva(s)': ('{0} new subject(s)','{0} nouvelle(s) matière(s)','{0} disciplina(s) nova(s)','{0} nuove materie','{0} neue(s) Fach/Fächer'),
'{0} tema(s) nuevo(s)': ('{0} new topic(s)','{0} nouveau(x) thème(s)','{0} tema(s) novo(s)','{0} nuovi argomenti','{0} neue(s) Thema/Themen'),
'{0} cuestionario(s) nuevo(s)': ('{0} new quiz(zes)','{0} nouveau(x) questionnaire(s)','{0} questionário(s) novo(s)','{0} nuovi quiz','{0} neue(s) Quiz'),
'{0} reemplazado(s)': ('{0} replaced','{0} remplacé(s)','{0} substituído(s)','{0} sostituiti','{0} ersetzt'),
'{0} conservado(s) como estaban': ('{0} kept as they were','{0} conservé(s) tel(s) quel(s)','{0} mantido(s) como estavam','{0} lasciati com’erano','{0} unverändert behalten'),
'{0} ya estaban igual': ('{0} were already the same','{0} étaient déjà identiques','{0} já estavam iguais','{0} erano già uguali','{0} waren schon gleich'),
'Recibido del PC:': ('Received from PC:','Reçu du PC :','Recebido do PC:','Ricevuto dal PC:','Vom PC empfangen:'),
'Recibido del móvil:': ('Received from phone:','Reçu du mobile :','Recebido do telemóvel:','Ricevuto dal telefono:','Vom Handy empfangen:'),
'Las carpetas no tienen cuestionarios todavía.': ('The folders don’t have any quizzes yet.','Les dossiers n’ont pas encore de questionnaires.','As pastas ainda não têm questionários.','Le cartelle non hanno ancora quiz.','Die Ordner haben noch keine Quizze.'),
'{0} cuestionario(s) no tienen ninguna tarjeta completa: no salen en Practicar, pero sí en ✎ Editar.': ('{0} quiz(zes) have no complete card: they don’t appear in Practice, but they do in ✎ Edit.','{0} questionnaire(s) n’ont aucune carte complète : ils n’apparaissent pas dans S’entraîner, mais bien dans ✎ Modifier.','{0} questionário(s) não têm nenhum cartão completo: não aparecem em Praticar, mas sim em ✎ Editar.','{0} quiz non hanno nessuna scheda completa: non compaiono in Esercitati, ma sì in ✎ Modifica.','{0} Quiz haben keine vollständige Karte: Sie erscheinen nicht unter Üben, aber unter ✎ Bearbeiten.'),
'No he podido leer esa carpeta:': ('I couldn’t read that folder:','Impossible de lire ce dossier :','Não consegui ler essa pasta:','Non sono riuscito a leggere quella cartella:','Dieser Ordner konnte nicht gelesen werden:'),
'No he podido copiar a esa carpeta:': ('I couldn’t copy to that folder:','Impossible de copier dans ce dossier :','Não consegui copiar para essa pasta:','Non sono riuscito a copiare in quella cartella:','In diesen Ordner konnte nicht kopiert werden:'),
'No he podido leer esa carpeta.': ('I couldn’t read that folder.','Impossible de lire ce dossier.','Não consegui ler essa pasta.','Non sono riuscito a leggere quella cartella.','Dieser Ordner konnte nicht gelesen werden.'),
'Copiados {0} cuestionarios en la carpeta «Mis cuestionarios (del móvil)».': ('Copied {0} quizzes to the “Mis cuestionarios (del móvil)” folder.','{0} questionnaires copiés dans le dossier « Mis cuestionarios (del móvil) ».','Copiados {0} questionários para a pasta «Mis cuestionarios (del móvil)».','Copiati {0} quiz nella cartella «Mis cuestionarios (del móvil)».','{0} Quizze in den Ordner „Mis cuestionarios (del móvil)“ kopiert.'),
'Para pasarlos al PC: conecta el móvil por USB, copia esa carpeta al PC y en el PC pulsa «Recibir del móvil (carpeta)».': ('To move them to the PC: connect the phone via USB, copy that folder to the PC and on the PC click “Receive from phone (folder)”.','Pour les passer sur le PC : branchez le mobile en USB, copiez ce dossier sur le PC et, sur le PC, cliquez sur « Recevoir du mobile (dossier) ».','Para os passar para o PC: liga o telemóvel por USB, copia essa pasta para o PC e no PC carrega em «Receber do telemóvel (pasta)».','Per passarli al PC: collega il telefono via USB, copia quella cartella sul PC e sul PC premi «Ricevi dal telefono (cartella)».','Um sie auf den PC zu bringen: Handy per USB verbinden, den Ordner auf den PC kopieren und am PC auf „Vom Handy empfangen (Ordner)“ klicken.'),
'Editar': ('Edit','Modifier','Editar','Modifica','Bearbeiten'),
'Aún no tienes cuestionarios': ('You don’t have any quizzes yet','Vous n’avez pas encore de questionnaires','Ainda não tens questionários','Non hai ancora quiz','Du hast noch keine Quizze'),
'Pásalos desde el PC o créalos aquí.': ('Bring them over from the PC or create them here.','Transférez-les depuis le PC ou créez-les ici.','Passa-os do PC ou cria-os aqui.','Passali dal PC o creali qui.','Hole sie vom PC oder erstelle sie hier.'),
'Crear y editar en el móvil': ('Create and edit on the phone','Créer et modifier sur le mobile','Criar e editar no telemóvel','Crea e modifica sul telefono','Auf dem Handy erstellen und bearbeiten'),
'{0} cuestionarios para practicar': ('{0} quizzes to practise','{0} questionnaires pour s’entraîner','{0} questionários para praticar','{0} quiz per esercitarti','{0} Quizze zum Üben'),
'{0} sin tarjetas (en gris: tócalos para completarlos)': ('{0} without cards (in grey: tap them to complete them)','{0} sans cartes (en gris : touchez-les pour les compléter)','{0} sem cartões (a cinzento: toca neles para os completar)','{0} senza schede (in grigio: toccali per completarli)','{0} ohne Karten (grau: antippen zum Vervollständigen)'),
'toca uno para empezar o marca varios': ('tap one to start or tick several','touchez-en un pour commencer ou cochez-en plusieurs','toca num para começar ou marca vários','toccane uno per iniziare o spuntane diversi','tippe eines an oder markiere mehrere'),
'vacía': ('empty','vide','vazia','vuota','leer'),
'Todo': ('All','Tout','Tudo','Tutto','Alles'),
'Sin temas todavía': ('No topics yet','Pas encore de thèmes','Ainda sem temas','Ancora nessun argomento','Noch keine Themen'),
'añadir': ('add','ajouter','adicionar','aggiungi','hinzufügen'),
'vacío': ('empty','vide','vazio','vuoto','leer'),
'Tema': ('Topic','Thème','Tema','Argomento','Thema'),
'Sin cuestionarios todavía': ('No quizzes yet','Pas encore de questionnaires','Ainda sem questionários','Ancora nessun quiz','Noch keine Quizze'),
'incompleto': ('incomplete','incomplet','incompleto','incompleto','unvollständig'),
'completar': ('complete','compléter','completar','completa','vervollständigen'),
'sin tarjetas': ('no cards','sans cartes','sem cartões','senza schede','keine Karten'),
'Pasar entre el PC y el móvil (Wi‑Fi o USB)': ('Transfer between PC and phone (Wi‑Fi or USB)','Transférer entre le PC et le mobile (Wi‑Fi ou USB)','Passar entre o PC e o telemóvel (Wi‑Fi ou USB)','Trasferisci tra PC e telefono (Wi‑Fi o USB)','Zwischen PC und Handy übertragen (WLAN oder USB)'),
'Practicar marcados ({0})': ('Practise ticked ({0})','S’entraîner sur les cochés ({0})','Praticar marcados ({0})','Esercitati sugli spuntati ({0})','Markierte üben ({0})'),
'Escribe las 4 cifras del PIN que sale en el PC.': ('Type the 4 digits of the PIN shown on the PC.','Saisissez les 4 chiffres du code PIN affiché sur le PC.','Escreve os 4 dígitos do PIN que aparece no PC.','Scrivi le 4 cifre del PIN che compare sul PC.','Gib die 4 Ziffern der PIN vom PC ein.'),
'Conectando con {0}…': ('Connecting to {0}…','Connexion à {0}…','A ligar a {0}…','Connessione a {0}…','Verbinde mit {0}…'),
'Buscando el PC en la Wi‑Fi…': ('Looking for the PC on the Wi‑Fi…','Recherche du PC sur le Wi‑Fi…','À procura do PC na Wi‑Fi…','Ricerca del PC sulla Wi‑Fi…','Suche den PC im WLAN…'),
'No he podido recibir:': ('I couldn’t receive:','Impossible de recevoir :','Não consegui receber:','Non sono riuscito a ricevere:','Empfang fehlgeschlagen:'),
'Lo recibido no se entiende.': ('What was received can’t be understood.','Les données reçues sont illisibles.','O que foi recebido não se entende.','Ciò che è stato ricevuto non si capisce.','Das Empfangene ist nicht lesbar.'),
'<b>✓ Enviado al PC.</b> Mira el PC: allí se añade y, si algo ya existe con otro contenido, te pregunta.': ('<b>✓ Sent to the PC.</b> Look at the PC: it’s added there and, if something already exists with different content, it asks you.','<b>✓ Envoyé au PC.</b> Regardez le PC : c’est ajouté là-bas et, si quelque chose existe déjà avec un autre contenu, il vous le demande.','<b>✓ Enviado para o PC.</b> Olha para o PC: é lá adicionado e, se algo já existir com outro conteúdo, pergunta-te.','<b>✓ Inviato al PC.</b> Guarda il PC: lì viene aggiunto e, se qualcosa esiste già con un contenuto diverso, ti chiede.','<b>✓ An den PC gesendet.</b> Schau auf den PC: Dort wird es hinzugefügt, und wenn etwas mit anderem Inhalt schon existiert, wirst du gefragt.'),
'Pasos de un procedimiento': ('Steps of a procedure','Étapes d’une procédure','Passos de um procedimento','Passaggi di un procedimento','Schritte eines Vorgehens'),
'Clasificar en grupos': ('Sort into groups','Classer en groupes','Classificar em grupos','Classifica in gruppi','In Gruppen einordnen'),
'Afirmación': ('Statement','Affirmation','Afirmação','Affermazione','Aussage'),
'Enunciado': ('Instructions','Énoncé','Enunciado','Consegna','Aufgabe'),
'Título o pie de foto (opcional)': ('Title or caption (optional)','Titre ou légende (facultatif)','Título ou legenda (opcional)','Titolo o didascalia (facoltativa)','Titel oder Bildunterschrift (optional)'),
'Procedimiento o problema': ('Procedure or problem','Procédure ou problème','Procedimento ou problema','Procedimento o problema','Vorgehen oder Aufgabe'),
'Exportar tema': ('Export topic','Exporter le thème','Exportar tema','Esporta argomento','Thema exportieren'),
'Exportar cuestionario': ('Export quiz','Exporter le questionnaire','Exportar questionário','Esporta quiz','Quiz exportieren'),
'Importar tema': ('Import topic','Importer un thème','Importar tema','Importa argomento','Thema importieren'),
'Importar cuestionario': ('Import quiz','Importer un questionnaire','Importar questionário','Importa quiz','Quiz importieren'),
'+ Asignatura': ('+ Subject','+ Matière','+ Disciplina','+ Materia','+ Fach'),
'+ Tema': ('+ Topic','+ Thème','+ Tema','+ Argomento','+ Thema'),
'+ Cuestionario': ('+ Quiz','+ Questionnaire','+ Questionário','+ Quiz','+ Quiz'),
'Renombrar asignatura': ('Rename subject','Renommer la matière','Mudar o nome da disciplina','Rinomina materia','Fach umbenennen'),
'Renombrar tema': ('Rename topic','Renommer le thème','Mudar o nome do tema','Rinomina argomento','Thema umbenennen'),
'Renombrar cuestionario': ('Rename quiz','Renommer le questionnaire','Mudar o nome do questionário','Rinomina quiz','Quiz umbenennen'),
'Eliminar asignatura': ('Delete subject','Supprimer la matière','Eliminar disciplina','Elimina materia','Fach löschen'),
'Eliminar tema': ('Delete topic','Supprimer le thème','Eliminar tema','Elimina argomento','Thema löschen'),
'Eliminar cuestionario': ('Delete quiz','Supprimer le questionnaire','Eliminar questionário','Elimina quiz','Quiz löschen'),
'Esta asignatura ya existe.': ('This subject already exists.','Cette matière existe déjà.','Esta disciplina já existe.','Questa materia esiste già.','Dieses Fach gibt es schon.'),
'Este tema ya existe en esta asignatura.': ('This topic already exists in this subject.','Ce thème existe déjà dans cette matière.','Este tema já existe nesta disciplina.','Questo argomento esiste già in questa materia.','Dieses Thema gibt es in diesem Fach schon.'),
'Este cuestionario ya existe en este tema.': ('This quiz already exists in this topic.','Ce questionnaire existe déjà dans ce thème.','Este questionário já existe neste tema.','Questo quiz esiste già in questo argomento.','Dieses Quiz gibt es in diesem Thema schon.'),
'Ese archivo es una biblioteca completa.': ('That file is a whole library.','Ce fichier est une bibliothèque complète.','Esse ficheiro é uma biblioteca completa.','Quel file è una raccolta completa.','Diese Datei ist eine ganze Sammlung.'),
'Ese archivo es una asignatura.': ('That file is a subject.','Ce fichier est une matière.','Esse ficheiro é uma disciplina.','Quel file è una materia.','Diese Datei ist ein Fach.'),
'Ese archivo es un tema.': ('That file is a topic.','Ce fichier est un thème.','Esse ficheiro é um tema.','Quel file è un argomento.','Diese Datei ist ein Thema.'),
'Ese archivo es un cuestionario.': ('That file is a quiz.','Ce fichier est un questionnaire.','Esse ficheiro é um questionário.','Quel file è un quiz.','Diese Datei ist ein Quiz.'),
'guardado en este navegador': ('saved in this browser','enregistré dans ce navigateur','guardado neste navegador','salvato in questo browser','in diesem Browser gespeichert'),
'guardado en el PC': ('saved on the PC','enregistré sur le PC','guardado no PC','salvato sul PC','auf dem PC gespeichert'),
'guardado en la app': ('saved in the app','enregistré dans l’app','guardado na app','salvato nell’app','in der App gespeichert'),
'No encuentro el PC. Comprueba que el PC muestra el PIN (botón «Conectar con el móvil por Wi‑Fi»), que los dos estáis en la misma Wi‑Fi y que Windows dejó pasar a MyQuizzes. Si sigue sin salir, escribe la dirección en «¿No encuentra el PC?».': (
 'I can’t find the PC. Check that the PC shows the PIN (button “Connect to phone via Wi‑Fi”), that both are on the same Wi‑Fi and that Windows let MyQuizzes through. If it still doesn’t appear, type the address under “Can’t find the PC?”.',
 'PC introuvable. Vérifiez que le PC affiche le code PIN (bouton « Connecter le mobile par Wi‑Fi »), que les deux sont sur le même Wi‑Fi et que Windows a autorisé MyQuizzes. Sinon, saisissez l’adresse dans « Le PC est introuvable ? ».',
 'Não encontro o PC. Verifica se o PC mostra o PIN (botão «Ligar ao telemóvel por Wi‑Fi»), se ambos estão na mesma Wi‑Fi e se o Windows deixou passar o MyQuizzes. Se continuar sem aparecer, escreve o endereço em «Não encontra o PC?».',
 'Non trovo il PC. Controlla che il PC mostri il PIN (pulsante «Collega al telefono via Wi‑Fi»), che siate sulla stessa Wi‑Fi e che Windows abbia lasciato passare MyQuizzes. Se ancora non compare, scrivi l’indirizzo in «Non trova il PC?».',
 'PC nicht gefunden. Prüfe, ob der PC die PIN anzeigt (Schaltfläche „Mit dem Handy per WLAN verbinden“), ob beide im selben WLAN sind und ob Windows MyQuizzes durchgelassen hat. Klappt es nicht, gib die Adresse unter „PC wird nicht gefunden?“ ein.'),
'PIN incorrecto. Mira el que sale ahora en el PC.': ('Wrong PIN. Check the one on the PC now.','Code PIN incorrect. Regardez celui affiché maintenant sur le PC.','PIN incorreto. Vê o que aparece agora no PC.','PIN sbagliato. Guarda quello che compare ora sul PC.','Falsche PIN. Schau, welche jetzt am PC steht.'),
'El PC ya no está conectado. Vuelve a pulsar «Conectar con el móvil por Wi‑Fi» en el PC.': ('The PC is no longer connected. Click “Connect to phone via Wi‑Fi” on the PC again.','Le PC n’est plus connecté. Cliquez à nouveau sur « Connecter le mobile par Wi‑Fi » sur le PC.','O PC já não está ligado. Volta a carregar em «Ligar ao telemóvel por Wi‑Fi» no PC.','Il PC non è più collegato. Premi di nuovo «Collega al telefono via Wi‑Fi» sul PC.','Der PC ist nicht mehr verbunden. Klicke am PC erneut auf „Mit dem Handy per WLAN verbinden“.'),
'Hay demasiadas fotos para enviarlo de una vez por Wi‑Fi.': ('There are too many photos to send it all at once via Wi‑Fi.','Il y a trop de photos pour tout envoyer d’un coup par Wi‑Fi.','Há demasiadas fotos para enviar tudo de uma vez por Wi‑Fi.','Ci sono troppe foto per inviare tutto insieme via Wi‑Fi.','Zu viele Fotos, um alles auf einmal per WLAN zu senden.'),
'El móvil no está conectado a ninguna Wi‑Fi.': ('The phone isn’t connected to any Wi‑Fi.','Le mobile n’est connecté à aucun Wi‑Fi.','O telemóvel não está ligado a nenhuma Wi‑Fi.','Il telefono non è collegato a nessuna Wi‑Fi.','Das Handy ist mit keinem WLAN verbunden.'),
'Nombre del tema': ('Topic name','Nom du thème','Nome do tema','Nome dell’argomento','Name des Themas'),
'Nombre del cuestionario': ('Quiz name','Nom du questionnaire','Nome do questionário','Nome del quiz','Name des Quiz'),
'Pregunta': ('Question','Question','Pergunta','Domanda','Frage'),
'Nombre de la asignatura': ('Subject name','Nom de la matière','Nome da disciplina','Nome della materia','Name des Fachs'),
'El nombre no puede llevar estos caracteres:': ('The name can’t contain these characters:','Le nom ne peut pas contenir ces caractères :','O nome não pode ter estes caracteres:','Il nome non può contenere questi caratteri:','Der Name darf diese Zeichen nicht enthalten:'),
'El nombre puede tener 80 caracteres como máximo.': ('The name can be at most 80 characters long.','Le nom peut compter 80 caractères au maximum.','O nome pode ter no máximo 80 caracteres.','Il nome può avere al massimo 80 caratteri.','Der Name darf höchstens 80 Zeichen lang sein.'),
'El nombre no puede acabar en punto.': ('The name can’t end with a full stop.','Le nom ne peut pas se terminer par un point.','O nome não pode acabar em ponto.','Il nome non può finire con un punto.','Der Name darf nicht mit einem Punkt enden.'),
'Opciones (marca las correctas)': ('Options (tick the correct ones)','Options (cochez les bonnes)','Opções (marca as corretas)','Opzioni (spunta quelle corrette)','Optionen (richtige ankreuzen)'),
'Respuesta correcta': ('Correct answer','Bonne réponse','Resposta correta','Risposta corretta','Richtige Antwort'),
'Pasos, en orden': ('Steps, in order','Étapes, dans l’ordre','Passos, por ordem','Passaggi, in ordine','Schritte, der Reihe nach'),
'Parejas': ('Pairs','Paires','Pares','Coppie','Paare'),
'Grupos y sus elementos': ('Groups and their items','Groupes et leurs éléments','Grupos e os seus elementos','Gruppi e i loro elementi','Gruppen und ihre Elemente'),
'Mover a…': ('Move to…','Déplacer vers…','Mover para…','Sposta in…','Verschieben nach…'),
}
