// Pruebas del HTML en modo app Android: puente Android simulado + servidor PC real para el Wi‑Fi.
const {chromium}=require('playwright');
const fs=require('fs'),path=require('path'),cp=require('child_process'),os=require('os');
const SRC=path.resolve(__dirname,'../PC');const APP=path.resolve(__dirname,'../Android/app/src/main/assets/index.html');
const DIR=fs.mkdtempSync(path.join(os.tmpdir(),'mcand-'));
for(const f of ['creador-cuestionarios.html','servidor.py'])fs.copyFileSync(path.join(SRC,f),path.join(DIR,f));
fs.writeFileSync(path.join(DIR,'config.json'),'{"lang":"es"}');
fs.mkdirSync(path.join(DIR,'Mis cuestionarios/Mates/Tema 1'),{recursive:true});
fs.writeFileSync(path.join(DIR,'Mis cuestionarios/Mates/Tema 1/Sumas.json'),JSON.stringify({title:'Sumas',cards:[{t:'vf',q:'2+2=4',e:'',v:true},{t:'vf',q:'2+3=6',e:'',v:false}]}));
fs.writeFileSync(path.join(DIR,'Mis cuestionarios/Mates/Tema 1/Vacío.json'),JSON.stringify({title:'Vacío',cards:[]}));
const IP=cp.execSync("hostname -I | awk '{print $1}'").toString().trim();
let ok=0,bad=0;const fails=[];
const T=(n,c,i='')=>{if(c){ok++;console.log('  ✓',n)}else{bad++;fails.push(n+(i?' → '+i:''));console.log('  ✗',n,i)}};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
 T('el HTML de la app es idéntico al del PC',fs.readFileSync(APP,'utf8')==fs.readFileSync(path.join(SRC,'creador-cuestionarios.html'),'utf8'));
 const srv=(process.env.MQ_GO?cp.spawn(process.env.MQ_GO,['--base',DIR,'--no-abrir','--html',require('path').join(DIR,'creador-cuestionarios.html')]):cp.spawn('python3',['servidor.py'],{cwd:DIR}));let out='';srv.stdout.on('data',d=>out+=d);
 for(let i=0;i<30&&!/localhost:(\d+)/.test(out);i++)await sleep(200);const PORT=+out.match(/localhost:(\d+)/)[1];
 const b=await chromium.launch();const ctx=await b.newContext({viewport:{width:390,height:800},isMobile:true});
 const errs=[];const dialogs=[];const answers=[];
 const pc=await ctx.newPage();pc.on('pageerror',e=>errs.push('PC '+e.message));pc.on('dialog',async d=>{dialogs.push('PC '+d.message());await (answers.shift()===false?d.dismiss():d.accept())});
 await pc.goto(`http://localhost:${PORT}/`);await sleep(800);
 // almacén simulado del móvil (lo que hace MainActivity: guarda el árbol; aquí en memoria del proceso Node)
 let store=null,lang=null,prev=null,toast=[];
 await ctx.exposeFunction('nodeSave',j=>{store=j});await ctx.exposeFunction('nodeLang',l=>{lang=l});await ctx.exposeFunction('nodePrev',h=>{prev=h});await ctx.exposeFunction('nodeToast',m=>{toast.push(m)});
 await ctx.exposeFunction('nodeHttp',async(method,url,body)=>{try{const r=await fetch(url,{method,body});return [r.status,await r.text()]}catch(e){return [0,'']}});
 const m=await ctx.newPage();m.on('pageerror',e=>errs.push('M '+e.message));m.on('dialog',async d=>{dialogs.push('M '+d.message());await (answers.shift()===false?d.dismiss():d.accept())});
 const boot=async()=>{await m.addInitScript(([s,l,ip])=>{let S=s,L=l;const E=(c,d,e)=>setTimeout(()=>onAndroidFolder(c,d,e),30);
   const addr=(dir)=>dir||(ip+':8765');
   window.Android={load:()=>S,save:j=>{S=j;nodeSave(j);return ''},getLang:()=>L,setLang:x=>{L=x;nodeLang(x)},pickFolder(){},exportFile:n=>'Descargas/'+n,toast:x=>nodeToast(x),preview:h=>nodePrev(h),
    wifiReceive:(pin,dir)=>nodeHttp('GET',`http://${addr(dir)}/mc/tree?pin=${pin}`).then(([st,t])=>E('wifi',st==200?t:null,st==200?null:st==403?'pin':st==410?'cerrado':'nopc')),
    wifiSend:(pin,dir)=>nodeHttp('POST',`http://${addr(dir)}/mc/subir?pin=${pin}`,S).then(([st,t])=>E('wifisend',st==200?t:null,st==200?null:st==403?'pin':st==410?'cerrado':'nopc'))}},[store,lang,IP]);
   await m.goto('file:///'+APP);await sleep(500)};
 console.log('\n1. Primera vez en el móvil');
 await boot();
 T('pide el idioma la primera vez',await m.isVisible('.lsh'));
 await m.click('[data-lg="es"]');await sleep(700);await boot();
 T('recuerda el idioma',lang=='es'&&!(await m.isVisible('.lsh')));
 T('pantalla principal vacía con «Recibir del PC»',(await m.textContent('#home')).includes('Aún no tienes cuestionarios'));
 console.log('\n2. Recibir del PC por Wi‑Fi');
 await pc.click('#wifi');await sleep(800);const pin=(await pc.textContent('.wpin')).trim();
 await m.click('#hrec');await m.fill('#wpin','12');await m.click('#wgo');
 T('avisa si el PIN no tiene 4 cifras',(await m.textContent('#wst')).includes('4 cifras'));
 await m.fill('#wpin',pin==='0000'?'1111':'0000');await m.click('#wgo');await sleep(400);
 T('PIN incorrecto → aviso claro',(await m.textContent('#wst')).includes('PIN incorrecto'));
 await m.click('details summary');await m.fill('#wdir','127.0.0.1:1');await m.fill('#wpin',pin);await m.click('#wgo');await sleep(500);
 T('dirección mala → «No encuentro el PC»',(await m.textContent('#wst')).includes('No encuentro el PC'));
 await m.fill('#wdir','');await m.click('#wgo');await sleep(600);
 T('recibe: avisa con el resumen',dialogs.at(-1).includes('Recibido del PC')&&dialogs.at(-1).includes('1 asignatura'),dialogs.at(-1));
 T('avisa del cuestionario sin tarjetas',dialogs.at(-1).includes('no tienen ninguna tarjeta completa'));
 T('se guarda en el móvil',JSON.parse(store).f[0].n=='Mates');
 console.log('\n3. Pantalla principal');
 const home=await m.textContent('#home');
 T('muestra la asignatura con 1/2 para practicar',home.includes('Mates')&&home.includes('1/2'),home.slice(0,120));
 await m.click('.hn[data-o]');await m.click('.ht .hn[data-o]');await sleep(100);
 T('el vacío sale en gris con «añadir»',(await m.textContent('.hq.off')).includes('añadir'));
 await m.click('.hq .hn[data-p]');await sleep(200);
 T('tocar un cuestionario abre la práctica',prev&&prev.includes('2+2=4'));
 // simula la vista de práctica en el mismo origen file:// y contesta
 fs.writeFileSync('/tmp/and-prev.html',prev);const pv=await ctx.newPage();pv.on('pageerror',e=>errs.push('P '+e.message));
 await pv.goto('file:///tmp/and-prev.html');await sleep(200);
 for(let i=0;i<2;i++){const q=await pv.textContent('.q');await pv.click(`.opt[data-v="${q.includes('2+2')?1:0}"]`);await pv.click('#nx')}
 T('nota 10 en la práctica',(await pv.textContent('.score')).startsWith('10,0'));await pv.close();
 await m.evaluate(()=>onPreviewClosed());await sleep(100);
 T('al volver sale la mejor nota (10,0) en verde',(await m.textContent('.nb.g').catch(()=>''))=='10,0');
 await m.check('.hq .ck');await sleep(100);
 T('marcar muestra «Practicar marcados (1)»',(await m.textContent('#hsp')).includes('(1)')&&await m.isVisible('#hbar'));
 await m.click('#hsp');T('practicar marcados abre la práctica',prev.includes('Práctica'));
 await m.click('#hsq');
 console.log('\n4. Editar en el móvil');
 await m.click('.hq.off .hn');await sleep(300);
 T('tocar el vacío abre el editor en ese cuestionario',(await m.textContent('#etitle')).includes('Vacío'));
 await m.click('[data-t="vf"]');await m.fill('textarea[data-k="q"]','El agua moja');await sleep(500);
 T('lo editado se guarda en el móvil',JSON.parse(store).f[0].f[0].q.find(q=>q.title=='Vacío').cards.length==1);
 T('Atrás en el editor vuelve a Practicar',await m.evaluate(()=>onBack())===true&&!(await m.isHidden('#home')));
 T('Atrás en Practicar sale de la app',await m.evaluate(()=>onBack())===false);
 T('el que estaba vacío ya se puede practicar',(await m.textContent('#home')).includes('2 cuestionarios para practicar'));
 console.log('\n5. Exportar desde el móvil');
 await m.click('#hed');await m.click('#tree .tr:has-text("Sumas")');await m.click('#dl');await sleep(200);
 T('exportar avisa de dónde se guarda',toast.at(-1)&&toast.at(-1).startsWith('Guardado en Descargas'),toast.at(-1));
 await m.evaluate(()=>onBack());
 console.log('\n6. Enviar al PC por Wi‑Fi (con cambios)');
 await m.click('#hrec');await m.fill('#wpin',pin);answers.push(true);await m.click('#wup');await sleep(700);
 T('el móvil confirma el envío',(await m.textContent('#wst')).includes('Enviado al PC'));
 await sleep(2500);
 const vac=JSON.parse(fs.readFileSync(path.join(DIR,'Mis cuestionarios/Mates/Tema 1/Vacío.json'),'utf8'));
 T('el PC pregunta y reemplaza lo cambiado',dialogs.some(d=>d.startsWith('PC')&&d.includes('ya existen en el PC'))&&vac.cards.length==1,dialogs.filter(d=>d.startsWith('PC')).join(' | '));
 console.log('\n7. Recibir otra vez sin cambios');
 await m.fill('#wpin',pin);await m.click('#wgo');await sleep(600);
 T('todo igual → «ya estaban igual», sin preguntar',dialogs.at(-1).includes('ya estaban igual'),dialogs.at(-1));
 console.log('\n8. Cambiar idioma en el móvil');
 await m.click('#hlang');await m.click('[data-lg="fr"]');await sleep(300);await boot();
 T('la app pasa a francés',(await m.textContent('#home')).includes('Modifier')&&lang=='fr');
 T('los datos siguen después de cambiar de idioma',(await m.textContent('#home')).includes('Sumas')||(await m.textContent('#home')).includes('Mates'));
 T('ningún error de JavaScript',errs.length==0,errs.join(' | '));
 await pc.click('#wifi');await b.close();srv.kill();
 console.log(`\nAndroid (HTML): ${ok} bien, ${bad} mal`);if(fails.length)console.log('FALLOS:\n - '+fails.join('\n - '));
})().catch(e=>{console.error('ERROR',e);process.exit(1)});
